# IIPImage Dockerfile based on Debian Linux
#
# iipsrv: latest stable version from IIPImage apt repository
# - installs keyring and iipsrv apt package
# - starts HTTP and FCGI services
# - reads images from /images/
# - provides /fcgi-bin/iipsrv.fcgi and /iiif/ endpoints
#

FROM debian:stable-slim
ENV DEBIAN_FRONTEND=noninteractive

LABEL MAINTAINER=ruven@users.sourceforge.net
LABEL url="https://iipimage.sourceforge.io"
LABEL author="Ruven <ruven@users.sourceforge.net>"
EXPOSE 80 9000


# Install build dependencies
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
	ca-certificates \
	media-types \
	lighttpd \
	apt-transport-https \
	curl && \
    update-ca-certificates


# Install keyring and iipsrv
RUN curl -o /tmp/iipimage-keyring_1.0.0-1+trixie_all.deb https://iipimage.sourceforge.io/apt/debian/pool/main/i/iipimage-keyring/iipimage-keyring_1.0.0-1+trixie_all.deb && \
    dpkg -i /tmp/iipimage-keyring_1.0.0-1+trixie_all.deb && \
    apt-get update && \
    apt-get install --no-install-recommends -y iipimage-server


# Append lighttpd configuration to enable FCGI proxy forwarding to iipsrv
RUN env echo -e 'server.modules += ("mod_fastcgi")\n\
fastcgi.server = (\n\
  "/fcgi-bin/iipsrv.fcgi" => (("host"=>"0.0.0.0","port"=>9000,"check-local"=>"disable")),\n\
  "/iiif/" => (("host"=>"0.0.0.0","port"=>9000,"check-local"=>"disable"))\n\
)' >> /etc/lighttpd/conf-enabled/iipsrv.conf


# Create startup script which starts both lighttpd and iipsrv
RUN env echo -e "#!/bin/sh\n\
lighttpd -f /etc/lighttpd/lighttpd.conf \n\
iipsrv --bind \${HOST}:\${PORT}" > /usr/local/bin/run &&\
chmod u+x /usr/local/bin/run


# Set iipsrv environment defaults and execute startup script
ENV HOST="0.0.0.0" PORT="9000" LOGFILE="/dev/stdout" URI_MAP="iiif=>IIIF" VERBOSITY=6 FILESYSTEM_PREFIX="/images/"
ENTRYPOINT ["run"]
